<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Scopes\WorkspaceScope;

/**
 * Base entity for all tenant-scoped Eloquent models.
 * Generated by laravel-models-generator; this base class is hand-maintained.
 */
abstract class TenantAwareEntity extends Model
{
    protected static function booted(): void
    {
        // Apply the global WorkspaceScope to every subclass automatically.
        static::addGlobalScope(new WorkspaceScope());

        // Auto-fill workspace_id on model creation.
        static::creating(function (self $model): void {
            if (empty($model->workspace_id)) {
                $model->workspace_id = WorkspaceScope::getCurrentWorkspaceId();
            }
        });
    }

    public function workspace(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Workspace::class, 'workspace_id');
    }
}
