<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Concerns\BelongsToWorkspace;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Base entity for all tenant-scoped Eloquent models.
 * Generated by laravel-models-generator; this base class is hand-maintained.
 */
abstract class TenantAwareEntity extends Model
{
    use BelongsToWorkspace;
    use HasFactory;

    /**
     * Every Prizy tenant table uses a UUID primary key (DEFAULT gen_random_uuid()),
     * so the key is a non-incrementing string. Generated subclasses also carry a
     * #[Table(keyType: 'string', incrementing: false)] attribute; these properties
     * make the base class authoritative for any hand-written tenant entity.
     */
    public $incrementing = false;

    protected $keyType = 'string';
}
